//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by s1res.rc
//
#define IDS_APP_NAME                    1
#define IDC_BTN_CHOOSE_FG               3
#define IDC_BTN_CHOOSE_BG               4
#define IDS_ERROR                       10
#define IDS_ERROR_UNKNOWN               11
#define IDS_WARNING                     12
#define IDS_CLOSE_WARN                  13
#define IDS_OPEN_HELP_FAILED            14
#define IDS_OPEN_ITEM_FAILED            15
#define IDS_CLOSE_ITEM_FAILED           16
#define IDS_DRAGNDROP_FAILED            17
#define IDI_MAIN                        100
#define IDD_ABOUT                       100
#define IDR_MAIN                        100
#define IDB_NO_IMG                      100
#define IDS_FOPEN_FILTER                100
#define IDS_BROWSE_FILTER               101
#define IDI_OPEN                        102
#define IDD_OPTIONS                     102
#define IDS_BROWSE_CAPTION              102
#define IDS_FSAVE_FILTER                103
#define IDD_WIZ_IMPORT                  104
#define IDS_UNNAMED                     104
#define IDD_WIZ_PG_DEVICE               106
#define IDB_WIZARD                      107
#define IDI_WIZARD                      108
#define IDB_FONT_SHEET                  108
#define IDI_RELOAD                      109
#define IDB_FONT_SHEET_MASK             109
#define IDB_PROP_SHEET                  110
#define IDB_PROP_SHEET_MASK             111
#define IDB_IMAGE_SHEET                 112
#define IDB_IMAGE_SHEET_MASK            113
#define IDI_USER                        118
#define IDD_WIZ_PG_ACCESS               125
#define IDD_WIZ_PG_FINISH               126
#define IDR_RTF_PG_DEVICE               127
#define IDD_WIZ_EXPORT                  127
#define IDR_RTF_PG_ACCESS_RD            128
#define IDD_FW_PROP                     128
#define IDR_RTF_PG_FINISH_RD            129
#define IDR_RTF_PG_ACCESS_WR            130
#define IDR_RTF_PG_FINISH_WR            131
#define IDS_TVROOT_AFI                  200
#define IDS_TVROOT_FW                   201
#define IDS_TVROOT_RES                  202
#define IDS_PROPERTY_SHEET              250
#define IDS_STATUS_READY                300
#define IDS_STATUS_ITEMS                301
#define IDS_STATUS_STRINGS              302
#define IDS_STATUS_FIRMWARE             303
#define IDS_STATUS_AFI                  304
#define IDS_STATUS_OPEN                 353
#define IDS_STATUS_CLOSE                354
#define IDS_STATUS_CLOSE_ALL            355
#define IDS_STATUS_EDIT                 356
#define IDS_STATUS_FOPEN                357
#define IDS_STATUS_FCLOSE               358
#define IDS_STATUS_FSAVE                359
#define IDS_STATUS_IMPORT               360
#define IDS_STATUS_EXPORT               361
#define IDS_STATUS_PROPSHEET            362
#define IDS_TOOLTIP_IMAGE_MONO          400
#define IDS_TOOLTIP_IMAGE_OLED          401
#define IDS_FWI_FLASH_TYPE              500
#define IDS_FWI_FILE_ID                 501
#define IDS_FWI_INVALID_HEADER_CHKSUM   502
#define IDS_FWI_VENDOR_ID               503
#define IDS_FWI_PRODUCT_ID              504
#define IDS_FWI_VERSION                 505
#define IDS_FWI_DATE                    506
#define IDS_FWI_INFO                    507
#define IDS_FWI_MANUFACTURER            508
#define IDS_FWI_DEVICE_NAME             509
#define IDS_FWI_USB_ATTR                510
#define IDS_FWI_USB_ID                  511
#define IDS_FWI_USB_REV                 512
#define IDS_FWI_MISSING_DATA            513
#define IDS_FWI_INVALID_CHKSUM          514
#define IDS_FW_PROP_LANG                600
#define IDS_FW_PROP_BATTERY             601
#define IDS_FW_PROP_ONLINE              602
#define IDS_FW_PROP_REPLAY              603
#define IDS_DIO_DEVICE_OPEN             900
#define IDS_DIO_DEVICE_RECOVERY         901
#define IDS_DIO_DEVICE_V9               902
#define IDS_DIO_GIVEIO_VER              903
#define IDS_DIO_FLASH_OPEN              910
#define IDS_DIO_FLASH_NOT_FOUND         911
#define IDS_DIO_FLASH_CHIP              912
#define IDS_DIO_READ                    913
#define IDS_DIO_WRITE                   914
#define IDS_DIO_ERROR_RECOVERY          915
#define IDS_DIO_NO_BREC                 916
#define IDS_DIO_NO_FW                   917
#define IDS_DIO_DONE                    999
#define IDC_BTN_PREV                    1001
#define IDC_BTN_NEXT                    1002
#define IDC_CONTENT                     1003
#define IDC_RAD_IMGEDT_DEFAULT          1012
#define IDC_RAD_IMGEDT_MSPAINT          1013
#define IDC_RAD_IMGEDT_CUSTOM           1014
#define IDC_EDT_CUSTOM                  1015
#define IDC_BTN_CUSTOM                  1016
#define IDC_TXT_HTTP                    1019
#define IDC_EDT_KEY                     1022
#define IDC_TXT_USER                    1023
#define IDC_LIST                        1024
#define IDC_BTN_RELOAD                  1025
#define IDC_PROGRESS                    1027
#define IDC_TEXT                        1029
#define IDC_RAD_GIVEIO                  1030
#define IDC_RAD_ADFU                    1031
#define IDC_TXT_STATUS                  1034
#define IDC_TXT_SAMPLE                  1040
#define IDC_EDT_DATE                    1041
#define IDC_EDT_GENERAL                 1043
#define IDC_SLD_DISP                    1044
#define IDC_EDT_VER_A                   1045
#define IDC_EDT_VER_B                   1046
#define IDC_EDT_VER_C                   1047
#define IDC_EDT_MANUFACTURER            1048
#define IDC_EDT_DEV_NAME                1049
#define IDC_EDT_VENDOR_INF              1050
#define IDC_CMB_LANG                    1051
#define IDC_EDT_PROD_INF                1052
#define IDC_EDT_PROD_REV                1053
#define IDC_EDT_VID                     1054
#define IDC_EDT_PID                     1055
#define IDC_EDT_USB_DESC                1056
#define IDC_SLD_LIGHT                   1057
#define IDC_SLD_STANDBY                 1058
#define IDC_SLD_SLEEP                   1059
#define IDC_CMB_BATTERY                 1060
#define IDC_CMB_ONLINE                  1061
#define IDC_CMB_REPLAY                  1062
#define IDC_CHK_RADIO                   1063
#define IDC_TXT_DISP                    1064
#define IDC_TXT_LIGHT                   1065
#define IDC_TXT_STANDBY                 1066
#define IDC_TXT_SLEEP                   1067
#define IDC_EDT_MTP_MANUFACTURER        1068
#define IDC_EDT_MTP_INFO                1069
#define IDC_STATUS                      1069
#define IDC_EDT_MTP_VERSION             1070
#define IDC_EDT_MTP_VID                 1071
#define IDC_EDT_MTP_PID                 1072
#define IDC_EDT_MTP_INFO2               1073
#define IDC_EDT_MTP_SERIAL              1073
#define ID_FILE_EXIT                    40000
#define ID_FILE_SAVEAS                  40001
#define ID_FILE_IMPORT                  40002
#define ID_FILE_EXPORT                  40003
#define ID_HELP_OPEN                    40010
#define ID_HELP_ABOUT                   40011
#define ID_HELP_REGISTER                40012
#define ID_HELP_UPDATE                  40013
#define ID_EDIT_OPEN                    40020
#define ID_EDIT_CLOSE                   40021
#define ID_EDIT_CLOSEALL                40022
#define ID_EDIT_SELECTALL               40023
#define ID_EDIT_REFRESH                 40024
#define ID_EDIT_OPTIONS                 40025
#define ID_EDIT_CODEPAGE                40026
#define ID_KEY_TAB                      40500
#define ID_KEY_SH_TAB                   40501
#define ID_KEY_DEL                      40502
#define ID_CODEPAGE_DEFAULT             41000
#define ID_CODEPAGE_DEFAULT_URLENC      41001
#define ID_CODEPAGE_JAPANESE            41002
#define ID_CODEPAGE_KOREAN              41003
#define ID_CODEPAGE_SCHINESE            41004
#define ID_CODEPAGE_TCHINESE            41005
#define ID_CODEPAGE_ISO_LATIN1          41100
#define ID_CODEPAGE_ISO_LATIN2          41101
#define ID_CODEPAGE_ISO_LATIN3          41102
#define ID_CODEPAGE_ISO_BALTIC          41103
#define ID_CODEPAGE_ISO_CYRILLIC        41104
#define ID_CODEPAGE_ISO_ARABIC          41105
#define ID_CODEPAGE_ISO_GREEK           41106
#define ID_CODEPAGE_ISO_HEBREW          41107
#define ID_CODEPAGE_ISO_TURKISH         41108
#define ID_CODEPAGE_ISO_ESTONIAN        41109
#define ID_CODEPAGE_ISO_LATIN9          41110
#define ID_CODEPAGE_WIN_EUROPEAN        41200
#define ID_CODEPAGE_WIN_CYRILLIC        41201
#define ID_CODEPAGE_WIN_LATIN           41202
#define ID_CODEPAGE_WIN_HEBREW          41203
#define ID_CODEPAGE_WIN_TURKISH         41204
#define ID_CODEPAGE_WIN_GREEK           41205
#define ID_CODEPAGE_WIN_ARABIC          41206
#define ID_CODEPAGE_WIN_BALTIC          41207
#define ID_CODEPAGE_WIN_VIETNAMESE      41208
#define ID_HELP_DONATE                  42000

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        133
#define _APS_NEXT_COMMAND_VALUE         42001
#define _APS_NEXT_CONTROL_VALUE         1070
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
